title: Jonathan Yeh
logo: /assets/IMG_4029-1.png
description: Data analyst skilled in SQL, Python, and Excel, turning raw data into clear, actionable insights. Experienced across finance, marketing, and data engineering, I’m passionate about helping forward-thinking teams make smarter, faster decisions through analytics.
# show_downloads: true
theme: jekyll-theme-minimal 
