title: Jonathan Yeh
logo: /assets/IMG_4029-1.png
description: I am a data analyst with a strong foundation in SQL, Python, and R, experienced in turning complex datasets into actionable business insights. My background spans finance, marketing analytics, and data engineering, with projects ranging from predictive modeling to interactive dashboards. I’m seeking opportunities at forward-thinking companies that value data-driven decision making, where I can contribute to impactful analytics initiatives and help bridge the gap between technical solutions and business strategy.
# show_downloads: true
theme: jekyll-theme-minimal 
